### ISSUE TITLE
Update for Sublime 3

### ISSUE THREAD

**Issue by shayaans** [vipex/KIXtart.tmLanguage#1]
The new language syntax appears to want YAML 1.2 for Sublime Text 3.
Please update

**Comment by vipex** [comment]
The language has been created for Sublime 3, and seems to be still work as now.
What kind of issue are you having?

**Comment by shayaans** [comment]
I can't get your stuff installed. I tried to follow your instructions and Sublime Text 3 won't recognize KiX.
It's also missing from Package Control

On Wed, Sep 28, 2016 at 8:45 AM, Luca Ravizzotti notifications@github.com wrote:
The language has been created for Sublime 3, and seems to be still work as now.
What kind of issue are you having?

**Comment by vipex** [comment]
You are right, I forget to made a proper release, so it wasn't accessible in the package manager.
I've now released first (non pre-release) version and is now visible in Package Control.

Thanks
